### ISSUE TITLE
Property 'blockConcurrencyWhile' does not exist on type 'DurableObjectState'

### ISSUE THREAD

**Issue by wighawag** [cloudflare/durable-objects-typescript-rollup-esm#3]
Error :
```
src/index.ts → dist/index.mjs...
[!] (plugin typescript) Error: @rollup/plugin-typescript TS2339: Property 'blockConcurrencyWhile' does not exist on type 'DurableObjectState'.
src/counter.ts (9:16)

9     this.state.blockConcurrencyWhile(async () => {
                 ~~~~~~~~~~~~~~~~~~~~~

Error: @rollup/plugin-typescript TS2339: Property 'blockConcurrencyWhile' does not exist on type 'DurableObjectState'.
    at error (/home/wighawag/dev/wighawag/etherplay/testing-durable/node_modules/rollup/dist/shared/rollup.js:151:30)
    at throwPluginError (/home/wighawag/dev/wighawag/etherplay/testing-durable/node_modules/rollup/dist/shared/rollup.js:19344:12)
```

To reproduce :
```
wrangler generate testing-durable https://github.com/cloudflare/durable-objects-typescript-rollup-esm
cd testing-durable
npm i
npm run build
```

**Comment by koeninger** [comment]
see https://github.com/cloudflare/workers-types/pull/106

**Comment by koeninger** [comment]
fixed in the meantime in https://github.com/cloudflare/durable-objects-typescript-rollup-esm/pull/5
